name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa

      - name: Create deployment directory (if it doesn't exist)
        uses: appleboy/ssh-action@v0.1.10 # Use ssh-action for remote commands
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p /home/ubuntu/app # Or your desired directory
            chmod 755 /home/ubuntu/app # Set permissions

      - name: Copy build files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ./ # changed source to root of the repo
          target: /home/ubuntu/app

      - name: Deploy application
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            cd /home/ubuntu/app

            echo "✅ Current path: $(pwd)"
            echo "📦 Installing dependencies..."
            npm install

            echo "⚙️ Building app..."
            npm run build || { echo "❌ Build failed"; exit 1; }

            echo "🔁 Restarting PM2..."
            pm2 delete next-app || true
            pm2 start npm --name "next-app" -- start
            pm2 save
